[tool.poetry]
name = "fastapi-app"
version = "0.1.0"
author = ""

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "*"
uicorn = "*"
sqlalchemy = "*"
asyncpg = "*"
alembic = "*"
pydantic = "*"
pyjwt = "*"
passlib = "*"
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
